const mongoose = require('mongoose');

const groupSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    trim: true,
    maxlength: 100
  },
  description: {
    type: String,
    trim: true,
    maxlength: 500
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  members: [{
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    },
    phoneNumber: {
      type: String,
      required: true
    },
    name: {
      type: String,
      required: true
    },
    role: {
      type: String,
      enum: ['admin', 'member'],
      default: 'member'
    },
    joinedAt: {
      type: Date,
      default: Date.now
    },
    isActive: {
      type: Boolean,
      default: true
    }
  }],
  joinCode: {
    type: String,
    unique: true,
    required: false, // Will be generated by pre-save hook
    uppercase: true
  },
  isPinned: {
    type: Boolean,
    default: false,
    index: true,
  },
  isFavorite: {
    type: Boolean,
    default: false,
    index: true,
  },
  isActive: {
    type: Boolean,
    default: true
  },
  settings: {
    allowMemberInvite: {
      type: Boolean,
      default: true
    },
    allowFileSharing: {
      type: Boolean,
      default: true
    },
    allowLocationSharing: {
      type: Boolean,
      default: true
    },
    allowVoiceMessages: {
      type: Boolean,
      default: true
    },
    allowVideoMessages: {
      type: Boolean,
      default: true
    }
  },
  lastActivity: {
    type: Date,
    default: Date.now
  },
  groupImage: {
    type: String,
    default: null
  }
}, {
  timestamps: true
});

// Indexes for efficient queries
groupSchema.index({ joinCode: 1 });
groupSchema.index({ createdBy: 1, isActive: 1 });
groupSchema.index({ 'members.user': 1, isActive: 1 });
groupSchema.index({ isPinned: -1, lastActivity: -1 });

// Generate unique join code
groupSchema.pre('save', async function(next) {
  // Always generate joinCode if it doesn't exist
  if (!this.joinCode || this.joinCode.trim() === '') {
    let joinCode;
    let isUnique = false;
    let attempts = 0;
    
    while (!isUnique && attempts < 10) {
      // Generate 6-character alphanumeric code
      joinCode = Math.random().toString(36).substring(2, 8).toUpperCase();
      const existingGroup = await this.constructor.findOne({ joinCode });
      isUnique = !existingGroup;
      attempts++;
    }
    
    if (!isUnique) {
      // Fallback: use timestamp-based code
      joinCode = Date.now().toString(36).substring(5, 11).toUpperCase();
    }
    
    this.joinCode = joinCode;
  }
  next();
});

// Virtual for member count
groupSchema.virtual('memberCount').get(function() {
  return this.members.filter(member => member.isActive).length;
});

// Virtual for admin count
groupSchema.virtual('adminCount').get(function() {
  return this.members.filter(member => member.role === 'admin' && member.isActive).length;
});

// Method to add member
groupSchema.methods.addMember = function(userId, phoneNumber, name, role = 'member') {
  // Check if user is already a member
  const existingMember = this.members.find(member => 
    member.user && member.user.toString() === userId.toString()
  );
  
  if (existingMember) {
    if (!existingMember.isActive) {
      existingMember.isActive = true;
      existingMember.joinedAt = new Date();
    }
    return existingMember;
  }
  
  const newMember = {
    user: userId,
    phoneNumber,
    name,
    role,
    joinedAt: new Date(),
    isActive: true
  };
  
  this.members.push(newMember);
  this.lastActivity = new Date();
  return newMember;
};

// Method to remove member
groupSchema.methods.removeMember = function(userId) {
  const member = this.members.find(member => 
    member.user && member.user.toString() === userId.toString()
  );
  
  if (member) {
    member.isActive = false;
    this.lastActivity = new Date();
  }
  
  return member;
};

// Method to update member role
groupSchema.methods.updateMemberRole = function(userId, role) {
  const member = this.members.find(member => 
    member.user && member.user.toString() === userId.toString()
  );
  
  if (member) {
    member.role = role;
    this.lastActivity = new Date();
  }
  
  return member;
};

// Method to check if user is member
groupSchema.methods.isMember = function(userId) {
  return this.members.some(member => 
    member.user && member.user.toString() === userId.toString() && member.isActive
  );
};

// Method to check if user is admin
groupSchema.methods.isAdmin = function(userId) {
  return this.members.some(member => 
    member.user && member.user.toString() === userId.toString() && 
    member.role === 'admin' && member.isActive
  );
};

module.exports = mongoose.model('Group', groupSchema);
